### ISSUE TITLE
UFT8.

### ISSUE THREAD

**Issue by jmalmor** [timdietrich/luna#5]
Your project rule!!.

Now I am having a so rare issue. I use mysql with utf8_unicode_ci on database, tables and fields. In Localhost develper(my notebook), ubuntu and also centos server I am getting results like this on accents and especial characters of spanish, portuguese also.

Example:

mayor\ufffda  responde,  \ufffdAc\ufffdrcate a \ufffdl!\nPaz.

Instead my have to return

mayoría ¡ é É

I try to use encoding functions without correct results.

**Comment by jmalmor** [comment]
Solved.

At constructor method Add this line:

if DatabaseConnection.Connect then DatabaseConnection.SQLExecute "SET NAMES 'utf8'"

And in the SQLSELECTProcess method add this

.StringValue.DefineEncoding(Encodings.UTF8) on Record.Value( data.IdxField(i+1).Name ) = data.IdxField(i+1). Line, finally looks like this:

Record.Value( data.IdxField(i+1).Name ) = data.IdxField(i+1).StringValue.DefineEncoding(Encodings.UTF8).

**Comment by timdietrich** [comment]
Thanks for the feedback, Jose. I'm glad that you're finding Luna to be helpful.

In related projects, I'm using this:
DatabaseConnection.SQLExecute("set names utf8 collate utf8_general_ci; set character set utf8")

It's based on info from this thread:
[https://forum.xojo.com/10414-mysql-special-characters-utf-8/0](https://forum.xojo.com/10414-mysql-special-characters-utf-8/0)

I hope this helps.

Thanks again,

Tim
